### PR TITLE
Documentation changes 

### PR DESCRIPTION
**Pull request by anellenson**
added new lines/test

### CODE REVIEW

**Comment by ssolson** [comment]
Looking good

**Comment by ssolson** [comment]
You should merge but the other way. You want to pull Tim's changes into your PR.

If Tim pushed new changes you should pull those changes to your branch.

I believe you had the IntegralEnvision remote setup so you should 
`git pull IntegralEnvision tabbed_GUI`
Or the equivalent in your git GUI.

**Comment by ssolson** [comment]
Hey @anellenson do you need any help with documentation updates?

**Comment by ssolson** [comment]
@anellenson it looks like you did the reverse of what I suggested above. 

You merged your fork and branch (via a push) into the IntergralEnvision  tabbed_GUI  branch. So you have effectively merged this PR as it stands which is not ready as there are PNGs ect. 

This is not a big deal. I suggest you complete this PR and any fixes we need can be made via this PR.

**Comment by anellenson** [comment]
Oh dang, that's too bad. I thought I had it! Okay I will work on this today and complete the PR in the next few days (maybe today)

**Comment by anellenson** [comment]
notice an issue - when loading the Tanana River inputs, the "Baseline Directory" and "Device Directory" fields aren't filled out

**Comment by anellenson** [comment]
"critical Velocity" in Tanana river still unmasked in my version with updated Tabbed GUI... not sure if this code is updated with Tim's?

**Comment by anellenson** [comment]
What is the Model Probabilities file?

**Comment by ssolson** [comment]
> notice an issue - when loading the Tanana River inputs, the "Baseline Directory" and "Device Directory" fields aren't filled out. However, the tool still runs and produces outputs. What is the best way to start an issue?

There are 3 Tanana river tutorials. All of them load the correct inputs on the correct fields for me.

If I had to guess you are loading the Velocity tutorial and looking at the shear stress tab.

**Comment by ssolson** [comment]
> "critical Velocity" in Tanana river still unmasked in my version with updated Tabbed GUI... not sure if this code is updated with Tim's?

Have you downloaded the latest DEMO files?

**Comment by anellenson** [comment]
Also, I randomly get this error message, which is not reproducible:

**Comment by anellenson** [comment]
Yes, I have the latest demo files

**Comment by anellenson** [comment]
Okay that's right, when I pull the velocity.ini files the shear stress tab doesn't populate

**Comment by ssolson** [comment]
> Also, I randomly get this error message, which is not reproducible:
> 
> ```
> 
> An error has occurred while executing Python code: 
> 
> FileNotFoundError: [WinError 3] The system cannot find the path specified: '' 
> Traceback (most recent call last):
>   File "C:\Users/aellenson/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\seat_qgis_plugin\stressor_receptor_calc.py", line 707, in run
>     os.makedirs(output_folder_name, exist_ok=True) # create output directory if it doesn't exist
>   File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\os.py", line 225, in makedirs
>     mkdir(name, mode)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
> ```

This is throwing an error due to the output trying to create a blank folder at an unspecified location. Let's also revisit this after we are sure we have Tim's latest version.

**Comment by anellenson** [comment]
I'm running this command to pull Tim's change: 

`PS C:\Users\aellenson\OneDrive - Integral Consulting Inc\opt\seat\seat-qgis-plugin> git pull Integral tabbed_GUI
From https://github.com/IntegralEnvision/seat-qgis-plugin
 * branch            tabbed_GUI -> FETCH_HEAD
Already up to date.`

**Comment by ssolson** [comment]
> I'm running this command to pull Tim's change:
> 
> ```
> PS C:\Users\aellenson\OneDrive - Integral Consulting Inc\opt\seat\seat-qgis-plugin> git pull Integral tabbed_GUI
> From https://github.com/IntegralEnvision/seat-qgis-plugin
>  * branch            tabbed_GUI -> FETCH_HEAD
> Already up to date.
> ```

okay great. I can see you are pulling from the correct remote (fork) and branch.

I want to do a couple sanity checks real quick. Can you show me the output of the following commands

```
git remote -v
git branch
git log
````

In the remote is a simple sanity check to make sure we have both setup (which I believe we made sure on the last call but still just a good check).

On the branch I want to make sure you are still on the documentation branch. I believe you are.

On the log I just want the first output to make sure your local commit matches what I can see here.

**Comment by anellenson** [comment]
```
git remote -v
Integral        https://github.com/IntegralEnvision/seat-qgis-plugin.git (fetch)
Integral        https://github.com/IntegralEnvision/seat-qgis-plugin.git (push)
origin  https://github.com/anellenson/seat-qgis-plugin.git (fetch)
origin  https://github.com/anellenson/seat-qgis-plugin.git (push)
upstream        https://github.com/sandialabs/seat-qgis-plugin.git (fetch)
upstream        https://github.com/sandialabs/seat-qgis-plugin.git (push)
PS C:\Users\aellenson\OneDrive - Integral Consulting Inc\opt\seat\seat-qgis-plugin> git branch 
* documentation
  main
PS C:\Users\aellenson\OneDrive - Integral Consulting Inc\opt\seat\seat-qgis-plugin> git log 
commit 1d07175657c24a2aa0b51836f050de03bb3348ca (HEAD -> documentation)
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Tue May 14 09:44:36 2024 -0700

    edited documentation

commit 5270ee504934f2ab67e4f6c69bc64c59ef2e1397 (origin/documentation)
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Mon May 13 11:26:31 2024 -0700

    clarified tutorial updates

commit c4f6f37224c568fd5bec2d65c68b4bebeb9854c0
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Thu Apr 25 11:12:49 2024 -0700

    chnged input files webpage, also edited localize_input_files.py script not included in the repo

commit eb9adeeaa83f86212ab82afe0ad756807202da7e
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Fri Apr 19 09:33:32 2024 -0700

    made some updates to style files, deleted tutorial files

commit 79c400e0c77f663e919d68e8f933af446ec2e92d
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Fri Apr 19 09:04:18 2024 -0700

    removed lines

commit d2349a5aaee6144d9a852cabc7afd931396e141c
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Fri Apr 19 09:02:12 2024 -0700

    added liens/test

commit daa93cd71d821dfa60fce9861a832b1fdbaed976
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Fri Apr 19 08:43:06 2024 -0700

    deleted adjust style paths from repo

commit af3207e874497ffb2a8209d93d907d953ccb122d
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Fri Apr 19 08:28:31 2024 -0700

    added new lines

commit a12ee847b1bcf859c89abdd2a0c726656650b3f0 (Integral/tabbed_GUI, main)
Merge: 91f80e1 f744ada
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Wed Apr 17 16:23:33 2024 -0700

    Merge branch 'tabbed_GUI' of https://github.com/IntegralEnvision/seat-qgis-plugin into pr/31

commit f744ada9b265d1df085c247d953f78228e16cbdd
Merge: 736bc25 a0268e0
Author: tnelson-integral <tnelson@integral-corp.com>
Date:   Wed Apr 17 10:21:10 2024 -0400

    Merge branch 'tabbed_GUI' of https://github.com/IntegralEnvision/seat-qgis-plugin into tabbed_GUI

commit 736bc25c3956e3603d2a662cd4ee8c9d9d2c1dc3
Author: tnelson-integral <tnelson@integral-corp.com>
Date:   Wed Apr 17 10:20:46 2024 -0400

    vel_crit mask and prevent window close error

commit 49fe60729f3c533e9b7e8863491f3d27fbbdb643
Author: tnelson-integral <tnelson@integral-corp.com>
Date:   Wed Apr 17 09:56:53 2024 -0400

    mask velocity recptor to model data limits

commit d45119be94c1a556f863579225e70e888f3fe176
Author: tnelson-integral <tnelson@integral-corp.com>
Date:   Wed Apr 17 09:39:13 2024 -0400

    eliminates error when closing window without running

commit 91f80e19e458c9acd8ed19552d0ed176f7bf2421
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Tue Apr 16 14:46:37 2024 -0700

    edited images to add highlighted fields, adjusted figure name

commit a0268e03b1b0e851ded49fb7aaf4ab0e75a7bc70
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Tue Apr 16 14:43:09 2024 -0700

    small edits for style files

commit 77f67c6390e1de340ce15dc35534dc25d0512c50
Merge: a21a795 5933d6c
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Tue Apr 16 14:36:55 2024 -0700

    Merge branch 'tabbed_GUI' of https://github.com/IntegralEnvision/seat-qgis-plugin into pr/31

commit a21a79590206f85f6f0c2952dc37398e3b74d21e
Author: Ashley Ellenson <aellenson@integral-corp.com>
Date:   Tue Apr 16 14:33:14 2024 -0700

    updated style files module in documentation, added image

commit 3e3e6c38bb71b3c3ecb9263b981a396b1129677c
Author: tnelson-integral <tnelson@integral-corp.com>
Date:   Tue Apr 16 14:42:30 2024 -0400

    option to mask no value in receptor

commit f9efcc3fee2673472cb639a82e3725b5498e32fc
Author: tnelson-integral <tnelson@integral-corp.com>
Date:   Tue Apr 16 14:12:02 2024 -0400

    added testing scripts

commit 5933d6c3a35855fda53bf356f1f8e95f49f9ca62
Merge: 78f87f7 b1462da
Author: Tim Nelson <104927621+tnelson-integral@users.noreply.github.com>
Date:   Tue Apr 16 12:14:05 2024 -0400

    Merge pull request #3 from ssolson/tabbed_GUI

    Tutorial Cases Docs Updated
```

**Comment by ssolson** [comment]
Right now your local commit is: 1d07175657c24a2aa0b51836f050de03bb3348ca 
while your remote commit is : 5270ee504934f2ab67e4f6c69bc64c59ef2e1397

I can see in your logs where you merged Tim's branch so you are up to date locally.

Can you `git push origin documentation` so you remote is up to date with your local?

Other than that the next step is to still ensure that re downloading the tutorial files and re installing seat you still see the issue.

**Comment by anellenson** [comment]
Tim and I fixed the issue from before - I think we needed an update in files.

I am working through the documentation and find the the "modules" and the "GUI" sections are slightly confusing. What is the objective of each section? IMO, modules should explain the theory behind what's happening (i.e., the equations), and the GUI section should walk through file formats, variable names, and implementing the SEAT plugin. My latest commit reflects these changes for only the "shear stress" module. 

There are still small details that need to be worked out in the language to help clarify things.

I am compiling a list of questions to help clarify the documentation:

1. docs/src/gui/shear_stress/02_probabilities.rst:
    - what is the prescribed naming convention? The example in pacwave is simply "hydrodynamic_probabilities.txt", etc.
    - If Hs and Tp do not affect the analysis, why are they included?
  2. docs/src/modules/shear_stress.rst
      - What is meant by assessing the effect on shear stress? Does this module determine how the energy devices create additional shear stress and thus affects sediment mobility?

**Comment by ssolson** [comment]
@anellenson it sounds like you are proposing some pretty major changes to the documentation. 

The documentation layout is historical. I took Tim's PowerPoint sections and converted it to the documentation you see. The modules is still the information directly from Tim's original PowerPoint. I do not have the requisite knowledge to improve this and have asked for help in the past multiple times. 

I have focused my efforts on everything prior to the Modules because that is enough to use the software. If you are proposing major changes to the GUI at this point I would vote against it and suggest you do that in a follow on PR. If you are proposing major changes to the modules I would also suggest that goes in a follow on PR. 

Your specific questions above (1. and 2. ) are best answered by @tnelson-integral.

**Comment by ssolson** [comment]
@anellenson any updates on this PR?

**Comment by anellenson** [comment]
@ssolson Tim and I have been working together to organize the layout of the documentation and answer the questions that I posed above. No major changes to the GUI, just changes to the documentation language. 

We want to pull some of the documentation from the code into the documentation, however. Sphinx should have an automatic way of doing this, is this something you can assist with?

**Comment by ssolson** [comment]
We could use sphinx autodoc or pdoc.

I agree API docs is a great idea. Adding this is not a minor change to the current PR though.

Is there something innate that you guys see that there must be API docs to get this PR passed?

I really recommend getting the major tabbed GUI into master and having a follow on PRs to improve it.

**Comment by anellenson** [comment]
@tnelson-integral thought that the modules should be able to be used stand alone (without the GUI) and so thought adding the documentation would be helpful for people who might want to use it this way. Maybe it's not pressing for this PR, however, and at this moment and can be something for future additions. 

@ssolson I can do this if you want to point me in the right direction when it's the right time, we could schedule a call.

**Comment by tnelson-integral** [comment]
Ashley and Sterling,
I am fine with pushing the tabbed GUI to Main. Ashley has some good updates to the documentation that can be added soon, and then the API updates can be refined as a future PR.
-Tim

Tim Nelson (he/him/his) | Project Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________

**Comment by anellenson** [comment]
I will finish committing this week and then we can finish the pull request

**Comment by ssolson** [comment]
Hey @anellenson I am here to help as you look to close out this PR.

**Comment by anellenson** [comment]
okay @ssolson this is ready to be pulled in

**Comment by anellenson** [comment]
however this gets merged

**Comment by ssolson** [comment]
Thanks @anellenson! I'll review it tomorrow.

**Review by ssolson — APPROVED** [review]
@anellenson I think you did a great job on this. I love that you renamed the GUI. I always thought that was a terrible name but I couldn't think of better. I only saw a couple of small issues things such as the formatting of paths in code blocks that I think could be improved. That said it is not wrong and I think we should get this major update to SEAT done and address small issues in small PRs.

I do not not have permissions to merge this branch @tnelson-integral could you?

**Comment by ssolson** [comment]
@anellenson you may need to convert this from a draft to read PR

**Comment by anellenson** [comment]
thanks @ssolson ! ready to be merged

**Comment by ssolson** [comment]
I do not have write access to the Integral branch so this is either you or @tnelson-integral 
image

**Comment by tnelson-integral** [comment]
Hi Ashley and Sterling,
I merged the documentation to Integrals Tabbed Gui branch.
-Tim

Tim Nelson (he/him/his) | Project Scientist
Tel: 561.240.5096 | Cell: 803.319.3344 | St. Petersburg | FL
***@***.*** | Bio<https://www.integral-corp.com/staff/timothy-r-nelson-ph-d>

<https://www.integral-corp.com/>[cid:integral_1a04a855-2877-4c4f-bd98-b89de3950d0f.png]<https://www.integral-corp.com/>

________________________________

**Pull request merged**
